kind: pipeline
name: default

steps:
  - name: base
    image: plugins/docker
    settings:
      repo: v7lin/depot_tools
      context: docker/depot_tools
      dockerfile: docker/depot_tools/Dockerfile
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
      tags:
        - latest
#    when:
#      event:
#        - tag
  - name: publish
    image: plugins/docker
    settings:
      repo: v7lin/flutter-jit
      context: docker/build
      dockerfile: docker/build/Dockerfile
      target: prod
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
      tags:
        - latest
#        - ${DRONE_TAG}
#    when:
#      event:
#        - tag